spring:
  # Enable ANSI colors in console output for better development experience
  output:
    ansi:
      enabled: always

  # Redis Configuration for token blacklist
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      timeout: 2000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms

  # Exclude database auto-configuration since API Gateway doesn't need database
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          # Disabled - using RouteLocator bean in GatewayRoutesConfig instead
          enabled: false
      forwarded:
        enabled: false

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

info:
  app:
    name: API Gateway
    description: E-commerce Gateway Server Application
    version: 1.0.0

# Token blacklist configuration
token:
  blacklist:
    prefix: ${TOKEN_BLACKLIST_PREFIX:auth}

# Global Rate Limiting Configuration
rate-limit:
  enabled: ${RATE_LIMIT_ENABLED:true}
  # Global limits per IP address
  per-ip:
    capacity: ${RATE_LIMIT_IP_CAPACITY:1000}        # Max requests
    refill-tokens: ${RATE_LIMIT_IP_REFILL:1000}     # Tokens to refill
    refill-period-minutes: ${RATE_LIMIT_IP_PERIOD:1} # Refill period in minutes
  # Global limits per authenticated user
  per-user:
    capacity: ${RATE_LIMIT_USER_CAPACITY:10000}
    refill-tokens: ${RATE_LIMIT_USER_REFILL:10000}
    refill-period-minutes: ${RATE_LIMIT_USER_PERIOD:1}

# Eureka configuration for development
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5  # Faster discovery for development
    initial-instance-info-replication-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # Faster heartbeat for development
    lease-expiration-duration-in-seconds: 30  # Faster eviction for development
    hostname: localhost

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true

    urls:
      - url: /v3/api-docs
        name: API Gateway
      # Service APIs - using automatic discovery pattern /api/{service-name}/**
      - url: /api/user-service/v3/api-docs
        name: User Service
      - url: /api/product-catalog-service/v3/api-docs
        name: Product Catalog Service
      - url: /api/shopping-cart-service/v3/api-docs
        name: Shopping Cart Service
      - url: /api/order-service/v3/api-docs
        name: Order Service
      - url: /api/payment-service/v3/api-docs
        name: Payment Service
      - url: /api/notification-service/v3/api-docs
        name: Notification Service

# JWT Configuration for development (must match user-service configuration)
jwt:
  secret: ${JWT_SECRET:CHANGE_THIS_IN_PRODUCTION_MUST_BE_AT_LEAST_256_BITS_LONG_FOR_HS256_ALGORITHM}
  issuer: ${JWT_ISSUER:ecommerce-platform}

# Development logging configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n"
  level:
    root: INFO
    '[org.springframework.cloud.gateway]': DEBUG
    '[reactor.netty.http.client]': DEBUG
    '[org.de013.apigateway.security]': DEBUG
    '[org.de013.apigateway]': DEBUG
