spring:
  # Enable ANSI colors in console output
  output:
    ansi:
      enabled: always

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    placeholder-replacement: false
  
# Kafka disabled for simple notification service
  # kafka:
  #   bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  
  mail:
    # SMTP Configuration - supports Gmail, Outlook, SendGrid, etc.
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
        debug: false
    # Test connection on startup
    test-connection: false
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

info:
  app:
    name: Notification Service
    description: Email and SMS notification service
    version: 1.0.0

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    docExpansion: none
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
  show-actuator: true
  group-configs:
    - group: 'notification-service-v1'
      display-name: 'Simple Notification Service API (v1)'
      paths-to-match:
        - '/api/v1/notificationsv/**'
        - '/actuator/**'

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{trace_id:-},%X{span_id:-}] ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{trace_id:-},%X{span_id:-}] ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%15.15t] %-40.40logger{39} : %m%n"
  level:
    "[org.de013.notificationservice]": DEBUG

# Simple notification service configuration
app:
  notification:
    email:
      enabled: true
      default-sender: noreply@ecommerce.com
      default-sender-name: E-Commerce Platform
    sms:
      enabled: true
      mock-mode: false  # Set to false for production with real Twilio credentials
      provider-name: TWILIO
      account-sid: ${TWILIO_ACCOUNT_SID:your_account_sid_here}
      auth-token: ${TWILIO_AUTH_TOKEN:your_auth_token_here}
      sender-number: ${TWILIO_PHONE_NUMBER:your_twilio_phone_number_here}
