spring:
  # Enable ANSI colors in console output
  output:
    ansi:
      enabled: always

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_catalog_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutes default TTL
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "product-catalog:"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Disable statistics logging
        generate_statistics: false
        # Performance optimizations
        jdbc:
          batch_size: 25
          fetch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        query:
          plan_cache_max_size: 2048
          in_clause_parameter_padding: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    mixed: true  # Allow mixed transactional and non-transactional statements

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  show-actuator: true
  group-configs:
    - group: 'product-catalog-service-v1'
      display-name: 'Product Catalog Service API (v1)'
      paths-to-match:
        - '/products/**'
        - '/categories/**'
        - '/actuator/**'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

logging:
  level:
    org.de013.productcatalog: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    # Disable Hibernate statistics logging
    org.hibernate.stat: WARN
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN

# Application specific configuration
app:
  product:
    cache:
      ttl: 600 # seconds
    search:
      max-results: 1000
      default-page-size: 20
    image:
      max-size: 5MB
      allowed-types: jpg,jpeg,png,webp
  # Security handled by API Gateway
  # No JWT or CORS configuration needed in microservices
