spring:
  # Enable ANSI colors in console output
  output:
    ansi:
      enabled: always

  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${SPRING_DATA_REDIS_DATABASE:0}
      timeout: 2000
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    repair: true

# Token blacklist configuration
token:
  blacklist:
    prefix: ${TOKEN_BLACKLIST_PREFIX:auth}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:CHANGE_THIS_IN_PRODUCTION_MUST_BE_AT_LEAST_256_BITS_LONG_FOR_HS256_ALGORITHM}
  expiration: ${JWT_EXPIRATION:900000}  # 15 minutes
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days
  issuer: ${JWT_ISSUER:ecommerce-platform}
  algorithm: ${JWT_ALGORITHM:HS256}

# Application Configuration
# CORS handled by API Gateway
app:
  security:
    password:
      min-length: ${PASSWORD_MIN_LENGTH:8}
      require-uppercase: ${PASSWORD_REQUIRE_UPPERCASE:true}
      require-lowercase: ${PASSWORD_REQUIRE_LOWERCASE:true}
      require-digit: ${PASSWORD_REQUIRE_DIGIT:true}
      require-special-char: ${PASSWORD_REQUIRE_SPECIAL:true}

    rate-limit:
      enabled: ${RATE_LIMIT_ENABLED:true}
      login-attempts: ${LOGIN_RATE_LIMIT:5}
      registration-attempts: ${REGISTRATION_RATE_LIMIT:3}
      general-requests: ${GENERAL_RATE_LIMIT:100}

    session:
      timeout: ${SESSION_TIMEOUT:1800}  # 30 minutes
      max-concurrent: ${MAX_CONCURRENT_SESSIONS:3}

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    docExpansion: none
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
  show-actuator: true
  group-configs:
    - group: 'user-service-v1'
      display-name: 'User Service API (v1)'
      paths-to-match:
        - '/users/**'
        - '/auth/**'
        - '/actuator/**'

logging:
  level:
    org.de013.userservice: DEBUG
    org.springframework.security: DEBUG
